= Integration weathermap prototype

== Developer Notes

Source files are in +scripts+ folder. To build a project, run:

 grunt build

This will create output files in the +dist+ folder.

If you never worked with http://nodejs.org[Node], refer to <<Setting up>> for instructions.

=== Setting up

Install http://nodejs.org[Node].

Install grunt-cli.

 npm install -g grunt-cli

Install dependencies (listed in +package.json+).

 npm install

=== Building process description

Three tasks are run during building:

useminPrepare::
Analyzes source +index.html+ and concatenates referenced js files into output folder. Using https://github.com/yeoman/grunt-usemin[grunt-usemin]
copy::
Copying source +index.html+ and config.js into output folder.
usemin::
Replaces scripts in the output +index.html+ with their concatenated versions. Using https://github.com/yeoman/grunt-usemin[grunt-usemin]

=== Important ===

Since arbor js performs some automatic path finding (to locate itself as javascript file), there is number of restrictions:

* arbor.js cannot be combined with other javascript files (so dont use any concat)
* arbor.js should be called exactly +arbor.js+ (without version)
* arbor.js should be in the folder, otherwise its path becomes "/" and url is broken
* no other javascript files should have +arbor+ in their name